apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: blob-farm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-farm
      tier: frontend
  template:
    metadata:
      labels:
        app: blob-farm
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: fabilier228/frontend-service:20250602-11
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"